
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Core.Identities;
using ServiceKit.Net;

namespace Core.Identities
{
	public partial interface IAccountRepository
	{
		/// <return>List<Identity.Account></return>
		public Task<Response<List<Identity.Account>>> getAllAccount(CallingContext ctx);

		/// <return>List<Identity.Account></return>
		public Task<Response<List<Identity.Account>>> getAccount(CallingContext ctx, string id);

		/// <return>Identity.Account</return>
		public Task<Response<Identity.Account>> createAccount(CallingContext ctx, Identity.Account account);

		/// <return>Identity.Account</return>
		public Task<Response<Identity.Account>> updateAccount(CallingContext ctx, Identity.Account account);


	}
}
