
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Core.Identities;
using ServiceKit.Net;

namespace Core.Identities
{
	public partial interface ILdapDomainRepository
	{
		/// <return>Ldap.LdapDomain</return>
		public Task<Response<Ldap.LdapDomain>> insertLdapDomain(CallingContext ctx, Ldap.LdapDomain ldapDomain);

		/// <return>Ldap.LdapDomain</return>
		public Task<Response<Ldap.LdapDomain>> updateLdapDomain(CallingContext ctx, Ldap.LdapDomain ldapDomain);

		/// <return>Ldap.LdapDomain</return>
		public Task<Response<Ldap.LdapDomain>> getLdapDomain(CallingContext ctx, string id);

		/// <return>List<Ldap.LdapDomain></return>
		public Task<Response<List<Ldap.LdapDomain>>> getAllLdapDomain(CallingContext ctx);


	}
}
