
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Core.Identities;
using ServiceKit.Net;

namespace Core.Identities
{
	public partial interface ILoginService
	{
		/// <return>ILoginIF_v1.LoginResultDTO</return>
		public Task<Response<ILoginIF_v1.LoginResultDTO>> LoginWithEmailPassword(CallingContext ctx, string email, string password);

		/// <return>ILoginIF_v1.LoginResultDTO</return>
		public Task<Response<ILoginIF_v1.LoginResultDTO>> LoginWithAD(CallingContext ctx, string username, string password);

		/// <return>ILoginIF_v1.TokensDTO</return>
		public Task<Response<ILoginIF_v1.TokensDTO>> Login2FA(CallingContext ctx, string code);

		/// <return>ILoginIF_v1.TokensDTO</return>
		public Task<Response<ILoginIF_v1.TokensDTO>> RefreshTokens(CallingContext ctx, string totp);

		/// <return>string</return>
		public Task<Response<string>> GetKAULoginURL(CallingContext ctx, string redirectUrl, string backendCallbackUrl);

		/// <return>ILoginService.KAUCallbackResponse</return>
		public Task<Response<ILoginService.KAUCallbackResponse>> KAUCallback(CallingContext ctx, string code, string state);


		public partial class KAUCallbackResponse : IEquatable<KAUCallbackResponse>
		{
			public string returnUrl { get; set; }
			public LoginIF.v1.LoginResultDTO tokens { get; set; }

			#region Clone 
			public virtual KAUCallbackResponse Clone()
			{
				KAUCallbackResponse clone = new();

				clone.returnUrl = new string(returnUrl.ToCharArray());

				// clone of tokens
				clone.tokens = tokens?.Clone();

				return clone;
			}
			#endregion Clone 

			#region Equals & HashCode 
			public bool Equals( KAUCallbackResponse other )
			{
				if (other is null) return false;

				if(returnUrl != other.returnUrl) return false;

				// equals of tokens
				if(tokens == null && other.tokens != null ) return false;
				if(tokens != null && tokens.Equals(other.tokens) == false ) return false;

				return true;
			}

			public override bool Equals(object obj) => Equals(obj as KAUCallbackResponse);

			public override int GetHashCode()
			{
				var hash = new HashCode();
				hash.Add(returnUrl);

				// hash of tokens
				if(tokens != null ) hash.Add(tokens);

				return hash.ToHashCode();
			}
			#endregion Equals & HashCode 
		}

	}
}
