apiVersion: v1
kind: Service
metadata:
  name: mongodb-external
  namespace: docratis-store
spec:
  type: NodePort
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      nodePort: 30001        # fix host-port a node felől
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
