
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>


namespace Core.Identities.Identity
{
	public enum AccountTypes
	{
		User,
		ExternalSystem,
		InternalService,
	}
}
