
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Core.Identities;

namespace Core.Identities.Identity
{
	public partial class Account : Core.Base.IBaseEntity, IEquatable<Account>
	{
		#region IBaseEntity
		public string id { get; set; }
		public string etag { get; set; }
		public DateTime LastUpdate { get; set; }
		#endregion IBaseEntity

		public AccountTypes Type { get; set; }
		public string Name { get; set; }
		public bool isActive { get; set; }
		public EmailAndPasswordAuth emailAndPasswordAuth { get; set; }
		public ADAuth adAuth { get; set; }
		public CertificateAuth certificateAuth { get; set; }
		public UgyfelkapuAuth ugyfelkapuAuth { get; set; }
		/// Optional two-factor authentication settings (TOTP, SMS, Email)
		public TwoFactorConfiguration twoFactor { get; set; }
		public List<ContactInfo> contacts { get; set; } = new();

		#region Clone 
		public virtual Account Clone()
		{
			Account clone = new();

			// begin: BaseEntity
			// end: BaseEntity

			clone.Type = Type;
			clone.Name = new string(Name.ToCharArray());
			clone.isActive = isActive;

			// clone of emailAndPasswordAuth
			clone.emailAndPasswordAuth = emailAndPasswordAuth?.Clone();

			// clone of adAuth
			clone.adAuth = adAuth?.Clone();

			// clone of certificateAuth
			clone.certificateAuth = certificateAuth?.Clone();

			// clone of ugyfelkapuAuth
			clone.ugyfelkapuAuth = ugyfelkapuAuth?.Clone();

			// clone of twoFactor
			clone.twoFactor = twoFactor?.Clone();

			// clone of contacts
			clone.contacts.AddRange( contacts.Select( v => v.Clone() ));

			return clone;
		}
		#endregion Clone 

		#region Equals & HashCode 
		public bool Equals( Account other )
		{
			if (other is null) return false;

			// begin: BaseEntity
			// end: BaseEntity

			if(Type != other.Type) return false;
			if(Name != other.Name) return false;
			if(isActive != other.isActive) return false;

			// equals of emailAndPasswordAuth
			if(emailAndPasswordAuth == null && other.emailAndPasswordAuth != null ) return false;
			if(emailAndPasswordAuth != null && emailAndPasswordAuth.Equals(other.emailAndPasswordAuth) == false ) return false;

			// equals of adAuth
			if(adAuth == null && other.adAuth != null ) return false;
			if(adAuth != null && adAuth.Equals(other.adAuth) == false ) return false;

			// equals of certificateAuth
			if(certificateAuth == null && other.certificateAuth != null ) return false;
			if(certificateAuth != null && certificateAuth.Equals(other.certificateAuth) == false ) return false;

			// equals of ugyfelkapuAuth
			if(ugyfelkapuAuth == null && other.ugyfelkapuAuth != null ) return false;
			if(ugyfelkapuAuth != null && ugyfelkapuAuth.Equals(other.ugyfelkapuAuth) == false ) return false;

			// equals of twoFactor
			if(twoFactor == null && other.twoFactor != null ) return false;
			if(twoFactor != null && twoFactor.Equals(other.twoFactor) == false ) return false;

			// equals of contacts
			if(contacts.SequenceEqual(other.contacts) == false ) return false;

			return true;
		}

		public override bool Equals(object obj) => Equals(obj as Account);

		public override int GetHashCode()
		{
			var hash = new HashCode();
			// begin: BaseEntity
			hash.Add(id);
			hash.Add(etag);
			hash.Add(LastUpdate);
			// end: BaseEntity

			hash.Add(Type);
			hash.Add(Name);
			hash.Add(isActive);

			// hash of emailAndPasswordAuth
			if(emailAndPasswordAuth != null ) hash.Add(emailAndPasswordAuth);

			// hash of adAuth
			if(adAuth != null ) hash.Add(adAuth);

			// hash of certificateAuth
			if(certificateAuth != null ) hash.Add(certificateAuth);

			// hash of ugyfelkapuAuth
			if(ugyfelkapuAuth != null ) hash.Add(ugyfelkapuAuth);

			// hash of twoFactor
			if(twoFactor != null ) hash.Add(twoFactor);

			// hash of contacts
			foreach( var element_contacts in contacts)
				hash.Add(element_contacts);

			return hash.ToHashCode();
		}
		#endregion Equals & HashCode 
	}

}
