
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Core.Identities;

namespace Core.Identities.Identity
{
	/// Base type for all authentication methods
	public partial class Auth : IEquatable<Auth>
	{
		public enum Methods
		{
			EmailAndPassword,
			ActiveDirectory,
			Certificate,
			KAU,
		}
		/// Defines the type of authentication method
		public Methods method { get; set; }

		#region Clone 
		public virtual Auth Clone()
		{
			Auth clone = new();

			clone.method = method;

			return clone;
		}
		#endregion Clone 

		#region Equals & HashCode 
		public bool Equals( Auth other )
		{
			if (other is null) return false;

			if(method != other.method) return false;

			return true;
		}

		public override bool Equals(object obj) => Equals(obj as Auth);

		public override int GetHashCode()
		{
			var hash = new HashCode();
			hash.Add(method);

			return hash.ToHashCode();
		}
		#endregion Equals & HashCode 
	}

}
