
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Core.Identities;

namespace Core.Identities.Identity
{
	/// Password-based authentication
	public partial class EmailAndPasswordAuth : Auth, IEquatable<EmailAndPasswordAuth>
	{
		public string email { get; set; }
		public bool isEmailConfirmed { get; set; }
		/// Hashed password
		public string passwordHash { get; set; }
		/// Salt used for hashing
		public string passwordSalt { get; set; }
		/// old password hashes
		public List<string> passwordHistory { get; set; } = new();
		/// password expiration time
		public DateOnly passwordExpiresAt { get; set; }
		/// Optional two-factor authentication settings (TOTP, SMS, Email)
		public TwoFactorConfiguration twoFactor { get; set; }

		#region Clone 
		public override EmailAndPasswordAuth Clone()
		{
			EmailAndPasswordAuth clone = new();

			// begin: Auth
			clone.method = method;
			clone.accountId = new string(accountId.ToCharArray());
			// end: Auth

			// begin: BaseEntity
			// end: BaseEntity

			clone.email = new string(email.ToCharArray());
			clone.isEmailConfirmed = isEmailConfirmed;
			clone.passwordHash = new string(passwordHash.ToCharArray());
			clone.passwordSalt = new string(passwordSalt.ToCharArray());

			// clone of passwordHistory
			clone.passwordHistory.AddRange( passwordHistory.Select( v => new string(v.ToCharArray()) ));
			clone.passwordExpiresAt = passwordExpiresAt;

			// clone of twoFactor
			clone.twoFactor = twoFactor?.Clone();

			return clone;
		}
		#endregion Clone 

		#region Equals & HashCode 
		public bool Equals( EmailAndPasswordAuth other )
		{
			if (other is null) return false;

			// begin: Auth
			if(method != other.method) return false;
			if(accountId != other.accountId) return false;
			// end: Auth

			// begin: BaseEntity
			// end: BaseEntity

			if(email != other.email) return false;
			if(isEmailConfirmed != other.isEmailConfirmed) return false;
			if(passwordHash != other.passwordHash) return false;
			if(passwordSalt != other.passwordSalt) return false;

			// equals of passwordHistory
			if(passwordHistory.SequenceEqual(other.passwordHistory) == false ) return false;
			if(passwordExpiresAt != other.passwordExpiresAt) return false;

			// equals of twoFactor
			if(twoFactor == null && other.twoFactor != null ) return false;
			if(twoFactor != null && twoFactor.Equals(other.twoFactor) == false ) return false;

			return true;
		}

		public override bool Equals(object obj) => Equals(obj as EmailAndPasswordAuth);

		public override int GetHashCode()
		{
			var hash = new HashCode();
			// begin: Auth
			hash.Add(method);
			hash.Add(accountId);
			// end: Auth

			// begin: BaseEntity
			hash.Add(id);
			hash.Add(etag);
			hash.Add(LastUpdate);
			// end: BaseEntity

			hash.Add(email);
			hash.Add(isEmailConfirmed);
			hash.Add(passwordHash);
			hash.Add(passwordSalt);

			// hash of passwordHistory
			foreach( var element_passwordHistory in passwordHistory)
				hash.Add(element_passwordHistory);
			hash.Add(passwordExpiresAt);

			// hash of twoFactor
			if(twoFactor != null ) hash.Add(twoFactor);

			return hash.ToHashCode();
		}
		#endregion Equals & HashCode 
	}

}
