// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Core.Auditing;
using PolyPersist;
using PolyPersist.Net.Attributes;

namespace Core.Identities.Ldap
{
	public partial class LdapDomainAuditTrail : IRow
	{
		string IEntity.PartitionKey { get => domainId; set => domainId = value; }
	}

}
