
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Core.Auditing;

namespace Core.Auditing
{

	/// audit trail bázis osztély, ebben lehet egy entity (root entity) változásait követni
	public partial interface IAuditTrail
	{
		string CreatePayload();
	}
}
