
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Core.Auditing;

namespace Core.Auditing
{

	/// audit trail bázis osztély, ebben lehet egy entity (root entity) változásait követni
	public partial interface IAuditTrail
	{
		public string id { get; set; }
		public string etag { get; set; }
		public DateTime LastUpdate { get; set; }
		public string PartitionKey { get; set; }
		public TrailOperations trailOperation { get; set; }
		public DateTime timestamp { get; set; }
		public string entityType { get; set; }
		public string entityId { get; set; }
		public string userId { get; set; }
		public string userName { get; set; }
		public string payload { get; set; }
	}
}
