
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>


namespace Core.Auditing
{

	public partial interface IAuditEventLog
	{
		public string operation { get; set; }
		public string operationDescription { get; set; }
		public string idenityId { get; set; }
		public string idenityName { get; set; }
		public string serviceName { get; set; }
		public string requestId { get; set; }
		public string correlationId { get; set; }
		public string payload { get; set; }
	}
}
