# kube-prometheus-stack values.yaml
# This file provisions Grafana + Prometheus and preloads Kong dashboards.

grafana:
  # Admin password for Grafana UI (user is "admin")
  adminPassword: "docratis"

  # Expose Grafana via the Kong Ingress Controller at http://grafana.docratis.local
  ingress:
    enabled: false
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true
      enforce_domain: false   # ne próbáljon fix domainre átirányítani
  
  # Provision Prometheus as default datasource + Alertmanager
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://monitoring-kube-prometheus-prometheus:9090
          isDefault: true
          editable: true
        - name: Alertmanager
          type: alertmanager
          access: proxy
          url: http://monitoring-kube-prometheus-alertmanager:9093
          isDefault: false
          jsonData:
            implementation: prometheus
            handleGrafanaManagedAlerts: false

  # Sidecars: enable dashboards, disable datasource sidecar to avoid duplicate provisioning
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      skipReload: true
      searchNamespace: ALL
    datasources:
      enabled: false

  # Dashboard provider for Kong
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "kong"
          orgId: 1
          folder: "Kong"
          type: file
          disableDeletion: true
          updateIntervalSeconds: 30
          options:
            path: /var/lib/grafana/dashboards/kong

  # Preload Kong dashboards from grafana.com (stored as ConfigMaps)
  dashboards:
    kong:
      kong-official:
        gnetId: 7424
        revision: 1
        datasource: Prometheus
      kong-ingress-controller:
        gnetId: 15662
        revision: 1
        datasource: Prometheus

prometheus:
  prometheusSpec:
    routePrefix: /prometheus
    externalUrl: /prometheus
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

# Fix for Docker Desktop
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
