# scylla/values.yaml
datacenter: docratis

racks:
  - name: r1
    members: 2
    scyllaConfig: scylla-auth-config
    storage:
      capacity: 10Gi
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 3Gi

scyllaImage:
  repository: scylladb/scylla
  tag: 5.4.9