
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

import { BFFRestClient } from "../../BFFRestClient";
import * as ProjectIF_v1 from "../../../types/TemplateManagement/Projects/ProjectIF_v1";
import { AxiosError } from 'axios';

const apiClient = BFFRestClient.getInstance().apiClient

export const ProjectIF = {
	V1: {
	async createProject(
		name:string,
		description:string,
		createdBy:string	) : Promise<ProjectIF_v1.ProjectSummaryDTO>
	{
		try {
			const response = await apiClient.post<ProjectIF_v1.ProjectSummaryDTO>(
				`/createproject/${encodeURIComponent(name)}/${encodeURIComponent(description)}/${encodeURIComponent(createdBy)}`
			);
			return response.value;
		}
		catch( error: AxiosError ) {
			throw apiClient.mapApiError(error, "createProject");
		}
	}
	,
	async updateProject(
		project:ProjectIF_v1.ProjectDetailsDTO	) : Promise<ProjectIF_v1.ProjectDetailsDTO>
	{
		try{
		}
		catch( error: AxiosError ) {
			throw apiClient.mapApiError(error, "updateProject");
		}
	}
	,
	async listAccessibleProjects(
			) : Promise<ProjectIF_v1.ProjectSummaryDTO[]>
	{
		try{
		}
		catch( error: AxiosError ) {
			throw apiClient.mapApiError(error, "listAccessibleProjects");
		}
	}
	,
	async listAccessibleProjectsForUser(
		urseId:string	) : Promise<ProjectIF_v1.ProjectSummaryDTO[]>
	{
		try{
		}
		catch( error: AxiosError ) {
			throw apiClient.mapApiError(error, "listAccessibleProjectsForUser");
		}
	}
	,
	async getProject(
		projectId:string	) : Promise<ProjectIF_v1.ProjectDetailsDTO>
	{
		try{
		}
		catch( error: AxiosError ) {
			throw apiClient.mapApiError(error, "getProject");
		}
	}
	,
	async addProjectAccess(
		projectId:string,
		identityId:string,
		role:ProjectIF_v1.ProjectAccessRoles	) : Promise<ProjectIF_v1.ProjectAccessDTO>
	{
		try{
		}
		catch( error: AxiosError ) {
			throw apiClient.mapApiError(error, "addProjectAccess");
		}
	}
	,
	}
}
