
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>


namespace TemplateManagement.Projects.Project
{
	public enum ProjectStatuses
	{
		/// A projekt még kialakítás alatt áll, sablonokat lehet hozzáadni, de nem éles.
		Draft,

		/// A projekt éles állapotban van, a benne lévő sablonokat használják, csak korlátozottan módosítható.
		Active,

		/// A projekt lezárva vagy lefagyasztva, tartalma nem módosítható (pl. audit miatt).
		Locked,

		/// A projekt kivezetett, csak olvasható, történeti célból van megtartva.
		Archived,

		/// A projekt törlésre lett jelölve, de még nem véglegesen törölt audit miatt.
		Deleted,

	}
}
