
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using TemplateManagement.Projects;

namespace TemplateManagement.Projects.Project
{

	public partial class ProjectHeader : IBase
	{
		#region IBase
		public string id { get; set; }
		public string etag { get; set; }
		public DateTime LastUpdate { get; set; }
		#endregion IBase

		public string Name { get; set; }
		public string Description { get; set; }
		public List<string> Tags { get; set; } = new();
		public ProjectStatuses Status { get; set; }
		public List<ProjectFolder> SubFolders { get; set; } = new();
		public DateTime CreatedAt { get; set; }
		public string CreatedBy { get; set; }

		#region Clone & Copy 
		virtual public ProjectHeader Clone()
		{
			ProjectHeader clone = new();

			// unfold begin: Base
			clone.id = new string(id.ToCharArray());
			clone.etag = new string(etag.ToCharArray());
			clone.LastUpdate = LastUpdate;
			// unfold end Base

			clone.Name = new string(Name.ToCharArray());
			clone.Description = new string(Description.ToCharArray());
			clone.Tags.AddRange( Tags.Select( v => new string(v.ToCharArray()) ));
			clone.Status = Status;
			clone.SubFolders.AddRange( SubFolders.Select( v => v.Clone() ));
			clone.CreatedAt = CreatedAt;
			clone.CreatedBy = new string(CreatedBy.ToCharArray());

			return clone;
		}
		#endregion Clone & Copy 
	}

}
