
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Core.Auditing;
using PolyPersist.Net.Attributes;

namespace TemplateManagement.Projects.Project
{
	public partial class ProjectAuditTrail : IBase, Core.Auditing.IAuditTrail, IEquatable<ProjectAuditTrail>
	{
		#region IBase
		public string id { get; set; }
		public string etag { get; set; }
		public DateTime LastUpdate { get; set; }
		#endregion IBase

		#region IAuditTrail
		public TrailOperations trailOperation { get; set; }
		public string entityType { get; set; }
		public string entityId { get; set; }
		public string idenityId { get; set; }
		public string idenityName { get; set; }
		public string payload { get; set; }
		public string previousTrailId { get; set; }
		public string deltaPayload { get; set; }
		[ClusteringColumn(1)]
		public DateTime timestamp { get; set; }
		#endregion IAuditTrail

		public string projectId { get; set; }

		#region Clone 
		public virtual ProjectAuditTrail Clone()
		{
			ProjectAuditTrail clone = new();

			// begin: Base
			// end: Base

			// begin: AuditTrail
			clone.trailOperation = trailOperation;
			clone.entityType = new string(entityType.ToCharArray());
			clone.entityId = new string(entityId.ToCharArray());
			clone.idenityId = new string(idenityId.ToCharArray());
			clone.idenityName = new string(idenityName.ToCharArray());
			clone.payload = new string(payload.ToCharArray());
			clone.previousTrailId = new string(previousTrailId.ToCharArray());
			clone.deltaPayload = new string(deltaPayload.ToCharArray());
			clone.timestamp = timestamp;
			// end: AuditTrail

			clone.projectId = new string(projectId.ToCharArray());

			return clone;
		}
		#endregion Clone 

		#region Equals & HashCode 
		public bool Equals( ProjectAuditTrail other )
		{
			if (other is null) return false;

			// begin: Base
			// end: Base

			// begin: AuditTrail
			if(trailOperation != other.trailOperation) return false;
			if(entityType != other.entityType) return false;
			if(entityId != other.entityId) return false;
			if(idenityId != other.idenityId) return false;
			if(idenityName != other.idenityName) return false;
			if(payload != other.payload) return false;
			if(previousTrailId != other.previousTrailId) return false;
			if(deltaPayload != other.deltaPayload) return false;
			if(timestamp != other.timestamp) return false;
			// end: AuditTrail

			if(projectId != other.projectId) return false;

			return true;
		}

		public override bool Equals(object obj) => Equals(obj as ProjectAuditTrail);

		public override int GetHashCode()
		{
			var hash = new HashCode();
			// begin: Base
			hash.Add(id);
			hash.Add(etag);
			hash.Add(LastUpdate);
			// end: Base

			// begin: AuditTrail
			hash.Add(trailOperation);
			hash.Add(entityType);
			hash.Add(entityId);
			hash.Add(idenityId);
			hash.Add(idenityName);
			hash.Add(payload);
			hash.Add(previousTrailId);
			hash.Add(deltaPayload);
			hash.Add(timestamp);
			// end: AuditTrail

			hash.Add(projectId);

			return hash.ToHashCode();
		}
		#endregion Equals & HashCode 
	}

}
