
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using IAM.Identities;

namespace IAM.Identities.Identity
{
	/// Base type for all authentication methods
	public partial class Auth : Core.Base.IBaseEntity, IEquatable<Auth>
	{
		public enum Methods
		{
			Email,
			ActiveDirectory,
			KAU,
			Certificate,
		}
		#region IBaseEntity
		public string id { get; set; }
		public string etag { get; set; }
		public DateTime LastUpdate { get; set; }
		#endregion IBaseEntity

		/// Defines the type of authentication method
		public Auth.Methods method { get; set; }
		public bool isActive { get; set; }
		public string accountId { get; set; }

		#region Clone 
		public virtual Auth Clone()
		{
			Auth clone = new();

			// begin: BaseEntity
			// end: BaseEntity

			clone.method = method;
			clone.isActive = isActive;
			clone.accountId = new string(accountId.ToCharArray());

			return clone;
		}
		#endregion Clone 

		#region Equals & HashCode 
		public bool Equals( Auth other )
		{
			if (other is null) return false;

			// begin: BaseEntity
			// end: BaseEntity

			if(method != other.method) return false;
			if(isActive != other.isActive) return false;
			if(accountId != other.accountId) return false;

			return true;
		}

		public override bool Equals(object obj) => Equals(obj as Auth);

		public override int GetHashCode()
		{
			var hash = new HashCode();
			// begin: BaseEntity
			hash.Add(id);
			hash.Add(etag);
			hash.Add(LastUpdate);
			// end: BaseEntity

			hash.Add(method);
			hash.Add(isActive);
			hash.Add(accountId);

			return hash.ToHashCode();
		}
		#endregion Equals & HashCode 
	}

}
